### ISSUE TITLE
react-cra example is failing 

### ISSUE THREAD

**Issue by Soumyaranjanpal** [stoplightio/elements#2346]
I have tried using this package with my existing application and got a lot of issues. So I tried a fresh installation from the codebase example/react-cra folder

I am getting the following error when trying to run the application.
`Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\Consulting\Open Source Packages\elements\examples\react-cra\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\Consulting\Open Source Packages\elements\examples\react-cra\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\Consulting\Open Source Packages\elements\examples\react-cra\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\Consulting\Open Source Packages\elements\examples\react-cra\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\Consulting\Open Source Packages\elements\examples\react-cra\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\Consulting\Open Source Packages\elements\examples\react-cra\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\Consulting\Open Source Packages\elements\examples\react-cra\node_modules\loader-runner\lib\LoaderRunner.js:214:10) 
    at iterateNormalLoaders (D:\Consulting\Open Source Packages\elements\examples\react-cra\node_modules\loader-runner\lib\LoaderRunner.js:221:10) 
D:\Consulting\Open Source Packages\elements\examples\react-cra\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\Consulting\Open Source Packages\elements\examples\react-cra\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\Consulting\Open Source Packages\elements\examples\react-cra\node_modules\webpack\lib\NormalModule.js:417:16)
    at D:\Consulting\Open Source Packages\elements\examples\react-cra\node_modules\webpack\lib\NormalModule.js:452:10
    at D:\Consulting\Open Source Packages\elements\examples\react-cra\node_modules\webpack\lib\NormalModule.js:323:13
    at D:\Consulting\Open Source Packages\elements\examples\react-cra\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\Consulting\Open Source Packages\elements\examples\react-cra\node_modules\loader-runner\lib\LoaderRunner.js:233:18
Failed to compile.

Failed to load config "@stoplight" to extend from.
Referenced from: D:\Consulting\Open Source Packages\elements\.eslintrc.js`

- Version used: ^7.0.0
- Environment name and version (e.g. Chrome 39, node.js 5.4): Node v18.12.1
- Operating System and version (desktop or mobile):
- Link to your environment/workspace/project:

**Comment by Soumyaranjanpal** [comment]
This is an issue, when you have already developed the FE using latest webpack from CRA and decide to use this package for the API documentation. Is there any alternatives I can use for my project ?
